import { RemissionGuideItemResponse } from './remission-guide-item.response';
import { RemissionGuideDriverResponse } from './remission-guide-driver.response';
import { ClientResponse } from './client.response';
import { ClientAddressResponse } from './client-address.response';
import { CarrierResponse } from './carrier.response';

export interface RemissionGuideResponse {
    id: number;
    documentSeriesId?: number;
    series?: string;
    sequence?: string;
    issueDate?: string;
    transferDate: string;
    transferReason: string;
    transferReasonDescription?: string;
    transportMode: string;
    grossWeight: number;
    weightUnit?: string;
    packageCount?: number;
    originAddress: string;
    originUbigeo: string;
    originLocalCode?: string;
    destinationAddress: string;
    destinationUbigeo: string;
    destinationLocalCode?: string;
    minorVehicleTransfer?: boolean;
    client?: ClientResponse;
    clientAddress?: string;
    selectedClientAddress?: ClientAddressResponse;
    carrier?: CarrierResponse;
    observations?: string;
    status: string;
    sunatResponseCode?: number;
    sunatMessage?: string;
    hashCode?: string;
    xmlUrl?: string;
    cdrUrl?: string;
    pdfUrl?: string;
    items: RemissionGuideItemResponse[];
    drivers?: RemissionGuideDriverResponse[];
}
